name: Build Fast Test APK

on:
  workflow_dispatch:
  push:
    branches:
      - virustotal-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Swapped 'standard' for 'normal' to match ObtainX's exact flavor names
      - name: Build Profile APK
        run: flutter build apk --profile --flavor normal

      - name: Upload Single APK
        uses: actions/upload-artifact@v4
        with:
          name: ObtainX-Fast-APK
          path: build/app/outputs/**/*.apk
          if-no-files-found: error
